### PR TITLE
117 fix broken coursemodule progress

### LINKED ISSUE #117: Fix broken course/module "progress"

### PR DESCRIPTION
**Pull request by Arnith86**
Changed / Created
- Percentage is now displayed both in courses and in modules (for student)
- Backend values are used.

Testing
- see if bar gets filled where applicable
- see if percentage is changed where applicable 

NOTE: i only use the values calculated on the backend, so if the values are wrong, then it is out of my hands. This issue is only related to the visual aspect of the progress-bar

### CODE REVIEW

File: src/features/shared/components/ProgressBar.tsx [hunk 1]
```diff
@@ -23,10 +25,17 @@ export const ProgressBar: React.FC<ProgressBarProps> = ({
   return (
     <div className={`progress-bar-container ${fullSize ? "full-size" : ""}`}>
       <span className="progress-bar-text">
-        {percentage}% <p>avklarat</p>
+        {preCalcPercentage ? preCalcPercentage : percentage}% <p>avklarat</p>
```
Comment (Bosseyang) [inline src/features/shared/components/ProgressBar.tsx]: preCalcPercentage needs to be presented as preCalcPercentage*100 here to get the % value and not just fractions of 100: `{preCalcPercentage ? preCalcPercentage * 100 : percentage}% <p>avklarat</p>`

**Review by Bosseyang — CHANGES_REQUESTED** [review]
Currently displays:
image

Small change required, check comment

File: src/features/shared/components/ProgressBar.tsx (hunk 1 above)
Comment (Arnith86) [reply src/features/shared/components/ProgressBar.tsx]: @Bosseyang  problem resolved

**Review by Bosseyang — APPROVED** [review]
Looks good, works as intended now!
Ready for merge!
